dist: trusty
language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
env:
  - VER=6.0.1
addons:
  apt:
    packages:
      - python-docutils
      - python-sphinx
before_install:
  - git clone -b varnish-$VER https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make &&
    sudo make install && sudo ldconfig && cd ..
  - sudo usermod -a -G varnish $USER
script:
  - sudo -E su $USER -c "$(which go) test -v"
